model_repository: /data
input_dirs: classification-data/input/
output_dirs: classification-data/output/
output_summary: summary.txt

best_model: model_300_10

base_model:
    min_count: 1
    cbow: 0
    negative: 5
    iter: 5

models:
   - model_200_6
   - model_200_10
