model_repository: models
input_dirs: classification-data/input/
output_dirs: classification-data/output/
output_summary: summary.txt

base_model:
    word2vec:
        min_count: 1
        cbow: 0
        negative: 5
        iter: 5
